#playbook for creating infra for ec2 instance in this will create vpc ,subnet,igw, route table and ec2 instance by calling role aws-infra.

- name: Create AWS Instance
  hosts: localhost
  gather_facts: false
  vars:
    instance_name: Ansible_instance2
  roles:
  - aws-infra


- name: Install Postgresql
  hosts: NewServer
  gather_facts: false
  become: yes
  become_method: sudo
  #roles:
  #  - linux_postgres_db_installation
  #  - linux_postgres_db_cretion
  tasks:
   
     - name: Install Java
       yum:
         name: java
         state: present
       become_method: sudo
       become_user: root

